input("Why didn't the paperclip cross the road?")
input("Because paperclips do not have legs")

input("Why didn't Bob cross the road?")
input("Because Bob lives in Texas and the road is in New York")

input("Why didn't Bob not cross the road?")
input("Because he moved to New York on a long flight to cross the road")
Choice1 = input("Would you like to remove Bob from the story?")
if Choice1 = yes input("Okay Bob is gone :)")
if Choice1 = no input("Bob will be gone in the next zero seconds :)")
input("Why did the narrator cross the road?")
input("Because I am filling in for bob")
if Choice1 = yes ("Why didn't bob cross the road?")
if Choice1 = yes ("Because you decided to get rid of him")
input ("Why did the road cross bob")
input ("Because the road moved to New York a on flight long cross Bob to")
print ("sdnoces75ninwodgnittuhs")
input ("Why did bob cross the road")
input ("because he is back")
if Choice1 = yes ("Bob is mad at you because you wanted to remove him from the story")
if Choice1 = no ("Bob is mad at the Narrator because he tricked you to getting rid of bob")
if choice1 = no ("Why did Bob take over the system")
if choice1 = no ("Because the narrator made jokes about bob and tricked you to getting rid oh him")
name = input("what is your name?")
print(f"Hello {name} and welcome to CT8")