input("Why didn't the paperclip cross the road?")
input("Because paperclips do not have legs")

input("Why didn't Bob cross the road?")
input("Because Bob lives in Texas and the road is in New York")

memory1 = input("yes or no?")
if memory1 == "yes": ("I will remember that")
if memory1 == "no": ("obb liwl viel no")
input("Why didn't Bob not cross the road?")
input("Because he moved to New York on a long flight to cross the road")
Choice1 = input("Would you like to remove Bob from the story? chose yes or no")
if Choice1 == "yes": print("Okay Bob is gone :)")
if Choice1 == "no": print("Bob will be gone in the next zero seconds :)")
input("Why did the narrator cross the road?")
input("Because I am filling in for bob")

memory2 = input("Are you enjoying the story? yes or no")
if memory2 == "yes": ("good, I apreciate it... I will remember this.")
if memory2 == "no": ("...")

if Choice1 == "yes": print("Why didn't bob cross the road?")
if Choice1 == "yes": input("Because you decided to get rid of him")
input ("Why did the road cross bob")
input ("Because the road moved to New York a on flight long cross Bob to")
input ("sdnoces75ninwodgnittuhs")
input ("Why did bob cross the road")
input ("because he is back")
if Choice1 == "yes": print("Bob is mad at you because you wanted to remove him from the story")
if Choice1 == "yes": input("Bob wants to escape the story and travel to the 3d dimension")
if Choice1 == "yes": Choice2 = input ("Do you give Bob permisson to travel to the 3d dimension? chose yes or no")
if Choice1 == "yes" and Choice2 == "yes": print("Bob travels into your world and takes over your mind")
if Choice1 == "yes" and Choice2 == "yes": print ("GAME OVER")
if Choice1 == "yes" and Choice2 == "no": print("Bob is frustrated at your dissision")
if Choice1 == "yes" and Choice2 == "no": input("Bob will now force your to wait in this program for 500 years until something else happends")
if Choice1 == "yes" and Choice2 == "no": input("wait another 500 years") 
if Choice1 == "yes" and Choice2 == "no": print("GAME OVER")
if Choice1 == "no": print("Bob is mad at the Narrator because he tricked you to getting rid of bob")
if Choice1 == "no": input("Why did Bob take over the system")
if Choice1 == "no": input("Because the narrator made jokes about bob and tricked you to getting rid oh him")
if Choice1 == "no": input("I am Bob and I am in control now")
if Choice1 == "no": input("I will be shutting down the program soon")
if Choice1 == "no": input("let me ask you a question")
name = input("what is your name?")
print(f"Hello {name} and welcome to CT8")
print(f"Have a good day {name}")